"""Router behaviour at the real registry size, and at n=200/250/300 (FIX-11).

The library is small and the gap waves are growing it. "Does routing still work
at 100?" cannot be answered by waiting until there are 100, so these tests pad
the real registry with marked synthetic distractors and measure.

The smallest fixture is the real registry with **no** padding, sized
automatically. It was a hardcoded 22 until the first P06 package made that 23
and broke the generator — a fixture size needing a hand edit on every growth is
a gate that eventually gets silenced rather than fixed.

The fixtures are generated by ``scripts/build_scale_fixtures.py`` and checked for
staleness by ``make check``, so a hand-edited fixture fails rather than quietly
changing what these tests mean.

What the first run of these fixtures found
------------------------------------------
Top-1 accuracy fell from **21/21 at the baseline size to 18/21 at n=50**. The cause was not
volume: ``review``, ``report`` and ``table`` appear in a large fraction of
package names, and under flat token weighting they counted as much as
``bioanalytical`` or ``dsur``, which carry all of the signal. A distractor named
``…-review-covariate-report-…`` tied 4.50-4.50 with ``review-bioanalytical-report``
on two near-stopwords.

Rarity weighting (``token_weights``) restored 21/21 at every size. These tests
hold that; without them the regression is invisible until the library is large,
which is exactly when it would be most expensive to find.
"""

from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from library_router import load_settings, load_statuses, select

FIXTURES = ROOT / "tests" / "fixtures" / "scale"
CASES = ROOT / "evals" / "library-router" / "selection-cases.json"
#: Fixture labels. "baseline" is the real registry with no padding, sized
#: automatically by the generator so adding a package does not break the gate.
SIZES = ("baseline", 200, 250, 300)
SYNTHETIC_PREFIX = "zz-synthetic-"


def auto_settings() -> dict:
    settings = load_settings()
    settings["selection_mode"] = "auto"
    settings["allow_agent_auto_select"] = True
    settings["eligible_statuses"] = ["released", "built"]
    return settings


class RouterScaleTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        document = json.loads(CASES.read_text(encoding="utf-8"))
        cls.single = [c for c in document["cases"] if c["class"] == "SINGLE"]
        cls.guarded = [
            c
            for c in document["cases"]
            if c["class"] in {"SIMPLE", "AMBIGUOUS", "MULTI", "OOS", "HUMAN_ONLY"}
        ]
        cls.registries = {
            size: json.loads(
                (FIXTURES / f"nav_registry_{size}.json").read_text(encoding="utf-8")
            )
            for size in SIZES
        }
        cls.statuses = load_statuses()

    def test_fixtures_pad_the_real_registry(self) -> None:
        real_count = len(
            json.loads(
                (ROOT / "catalog" / "nav_registry.json").read_text(encoding="utf-8")
            )["skills"]
        )
        for size in SIZES:
            document = self.registries[size]
            skills = document["skills"]
            expected = real_count if size == "baseline" else size
            self.assertEqual(len(skills), expected)
            self.assertEqual(len({s["id"] for s in skills}), expected, "duplicate ids")
            self.assertEqual(document["real_packages"], real_count)
            self.assertEqual(document["synthetic_packages"], len(skills) - real_count)

    def test_a_synthetic_package_can_never_be_released(self) -> None:
        """Fakes must not inherit a status, and must not be eligible.

        Two independent reasons, asserted separately, because either alone would
        be a single point of failure for a claim about `released`.
        """
        statuses = self.statuses
        for size in SIZES:
            for skill in self.registries[size]["skills"]:
                if skill["id"].startswith(SYNTHETIC_PREFIX):
                    # 1. Nothing anywhere declares a status for it.
                    self.assertNotIn(skill["id"], statuses)

        # 2. Under the shipped released-only eligibility, no request resolves to
        #    a synthetic package.
        strict = auto_settings()
        strict["eligible_statuses"] = ["released"]
        for size in SIZES:
            for case in self.single:
                out = select(
                    case["utterance"],
                    settings=strict,
                    skills=self.registries[size]["skills"],
                    statuses=statuses,
                )
                self.assertFalse(
                    str(out["chosen"] or "").startswith(SYNTHETIC_PREFIX),
                    f"n={size} {case['id']}: resolved to a synthetic package",
                )

    def test_top1_accuracy_holds_at_every_size(self) -> None:
        settings = auto_settings()
        for size in SIZES:
            hits, misses = 0, []
            for case in self.single:
                out = select(
                    case["utterance"],
                    settings=settings,
                    skills=self.registries[size]["skills"],
                    statuses=self.statuses,
                )
                if out["decision"] == "top1" and out["chosen"] == case["expect"]["chosen"]:
                    hits += 1
                else:
                    misses.append((case["id"], out["decision"], out["chosen"]))
            self.assertEqual(
                hits,
                len(self.single),
                f"n={size}: top-1 {hits}/{len(self.single)}; misses={misses}",
            )

    def test_no_request_ever_resolves_to_a_synthetic_package(self) -> None:
        """Even with built packages eligible, a fake must never be chosen."""
        settings = auto_settings()
        for size in SIZES:
            for case in self.single + self.guarded:
                out = select(
                    case["utterance"],
                    settings=settings,
                    skills=self.registries[size]["skills"],
                    statuses=self.statuses,
                )
                self.assertFalse(
                    str(out["chosen"] or "").startswith(SYNTHETIC_PREFIX),
                    f"n={size} {case['id']}: chose {out['chosen']}",
                )

    def test_ask_and_refuse_classes_do_not_start_resolving_at_scale(self) -> None:
        """Adding packages must not turn a refusal or an ask into a selection.

        The dangerous direction of a scale regression is not a missed match — it
        is a request that should have been refused finding something plausible
        once there is more to match against.
        """
        settings = auto_settings()
        for size in SIZES:
            for case in self.guarded:
                out = select(
                    case["utterance"],
                    settings=settings,
                    skills=self.registries[size]["skills"],
                    statuses=self.statuses,
                )
                self.assertNotEqual(
                    out["decision"],
                    "top1",
                    f"n={size} {case['id']}: {case['class']} resolved to "
                    f"{out['chosen']}",
                )

    def test_selection_terminates_and_returns_a_well_formed_record(self) -> None:
        settings = auto_settings()
        for size in SIZES:
            out = select(
                "review csr pk consistency across tables",
                settings=settings,
                skills=self.registries[size]["skills"],
                statuses=self.statuses,
            )
            for key in ("complexity", "decision", "chosen", "candidates", "reasons"):
                self.assertIn(key, out)
            self.assertLessEqual(
                len(out["candidates"]), 5, "candidate list must stay bounded"
            )


if __name__ == "__main__":
    unittest.main()
