"""The canonical definition of this repository's public surface.

Single source of record. ``validate_repo.py`` and ``privacy_scan.py`` both import
from here; neither keeps its own copy.

Why this module exists
----------------------
Both scripts previously defined ``PUBLIC_ROOTS`` and ``PUBLIC_ROOT_FILES``
independently, and on 2026-08-05 they drifted: ``.gitleaks.toml`` was added to
the validator's allowlist but not the scanner's. The validator enumerated 213
files, the privacy scanner 212, and the file the two disagreed about was
therefore never privacy-scanned at all.

Both scripts still passed. A duplicated boundary does not announce that it has
drifted — it just protects slightly different things, and the gap is exactly the
size of whatever was added to one copy and not the other.

Enumeration policy (PS-D018)
----------------------------
The public surface is enumerated by **allowlist**, never by a recursive
filesystem walk filtered through a denylist. A denylist fails silently on
anything nobody thought to list; on 2026-08-04 that defect made the public
tooling read the private ``_ADMIN/`` control plane. For a repository whose
premise is a privacy boundary, the enumeration source *is* the boundary.

Author: ClinPharm PMx Skills contributors
Date: 2026-08-05
Dependencies: Python standard library only — these gates must run from a clean
checkout with nothing installed.
"""

from __future__ import annotations

from pathlib import Path

#: Directories that constitute the public product. Anything outside this set is
#: not part of the public surface and is never read, whether or not it exists.
PUBLIC_ROOTS: frozenset[str] = frozenset(
    {
        ".github",
        ".githooks",
        ".claude-plugin",
        "catalog",
        "collections",
        "contexts",
        "docs",
        "evals",
        # Layer 1 — the 167-task job model, generated by scripts/build_map.py
        # from catalog/job-model-167.tsv. Added 2026-08-13 with the map itself:
        # an undeclared root is invisible to the privacy scan, so declaring it
        # is what puts the new surface under the gates rather than beside them.
        "map",
        "examples",
        "scripts",
        "shared",
        "site",
        "skills",
        "tests",
    }
)

#: Files permitted at the repository root.
PUBLIC_ROOT_FILES: frozenset[str] = frozenset(
    {
        ".editorconfig",
        ".gitattributes",
        ".gitignore",
        ".gitleaks.toml",
        "AGENTS.md",
        # `CLAUDE.md` and `GEMINI.md` are relative symlinks to `AGENTS.md`, not
        # copies. One contract, three filenames, because each host looks for a
        # different name and would otherwise read nothing.
        "CLAUDE.md",
        "GEMINI.md",
        "CHANGELOG.md",
        "CITATION.cff",
        # Moved here from `docs/` on 2026-08-13. A visitor checking whether the
        # published numbers are honest should not have to open a subdirectory.
        "CLAIM-LEDGER.md",
        "CODE_OF_CONDUCT.md",
        "CONTRIBUTING.md",
        "LICENSE",
        "Makefile",
        "README.md",
        "REFERENCES.md",
        "ROADMAP.md",
        "SECURITY.md",
        "SUPPORT.md",
        "pyproject.toml",
        "requirements.lock",
        ".pre-commit-config.yaml",
        # Skill scanners sit at the root deliberately. A visitor deciding whether
        # to install 151 packages from a stranger wants the trust surface where
        # the decision is made, not inside `scripts/`.
        "scan_skills.py",
        "scan_pr_skills.py",
        "plugin.json",
    }
)


def allowlist_walk(root: Path, ignored_parts: set[str] | None = None) -> list[Path]:
    """Enumerate the public surface under ``root`` by allowlist.

    ``ignored_parts`` drops paths containing any of the given path components
    (``__pycache__`` and similar). It is a second filter on an already-bounded
    set, never the mechanism that defines the surface.
    """
    skip = ignored_parts or {"__pycache__"}
    found: list[Path] = []
    for name in sorted(PUBLIC_ROOT_FILES):
        candidate = root / name
        if candidate.is_file():
            found.append(candidate)
    for name in sorted(PUBLIC_ROOTS):
        base = root / name
        if not base.is_dir():
            continue
        found.extend(
            path
            for path in sorted(base.rglob("*"))
            if path.is_file() and not any(part in skip for part in path.parts)
        )
    return sorted(found)
